// Generated by CoffeeScript 1.4.0
(function() {
  var App;

  App = (function() {

    function App() {
      this.albums = [];
      this.$view = $("#main");
    }

    App.prototype.setAlbums = function(data) {
      return this.albums = data;
    };

    App.prototype.initWithAlbums = function(data) {
      var $tableBody, album, html, row, _i, _len, _ref, _results;
      this.setAlbums(data);
      html = "<table id='table-albums' class='table'>\n  <thead>\n    <tr>\n      <th>Album</th>\n      <th>Representative Track</th>\n      <th>Genre</th>\n      <th>Play Count</th>\n    </tr>\n  </thead>\n  <tbody>\n  </tbody>\n</table>";
      this.$view.append(html);
      $tableBody = $("#table-albums tbody");
      _ref = this.albums;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        album = _ref[_i];
        row = "<tr><td>";
        if (album.MPMediaItemPropertyArtwork != null) {
          row = "" + row + "<img src='data:image/jpeg;base64," + album.MPMediaItemPropertyArtwork + "'>";
        }
        row = "  " + row + "<div>" + album.MPMediaItemPropertyAlbumTitle + "</div><div>" + album.MPMediaItemPropertyArtist + "</div></td>\n  <td>" + album.MPMediaItemPropertyTitle + "</td>\n  <td>" + album.MPMediaItemPropertyGenre + "</td>\n  <td>" + album.MPMediaItemPropertyPlayCount + "</td>\n</tr>";
        _results.push($tableBody.append(row));
      }
      return _results;
    };

    return App;

  })();

  window._app = new App;

}).call(this);
